### ISSUE TITLE
安装方式在虚拟主机有困难。

### ISSUE THREAD

**Issue by noqcom** [lizhichao/VicWord#3]
可以改为require方式吗?

还有似乎分词含有英文時很容易把中英文贴在一起。

词库太大消耗内存的问题，是不是可以改成slqite词典?

**Comment by noqcom** [comment]
似乎是词典不包含的词，无论中英文都会贴在一起。

建议改成词典没有的中文词一字一拆。
词典没有的英文数字直接拆出来，依据空白或标点分词。

**Comment by lizhichao** [comment]
你最新的测试看看 ，现在会按照标点符号分割
