### ISSUE TITLE
无法正确的获取分词

### ISSUE THREAD

**Issue by guihouchang** [lizhichao/VicWord#4]
use Lizhichao\Word\VicWord;

$data = [];
$fc = new VicWord('igb');
$data = $fc->getWord("我看看有什么分词效果");

返回结果：

[
  [
    "我看看有什么分词效果",
    30,
    null,
    0
  ]

**Comment by lizhichao** [comment]
你没有定义词典路径
//定义词典文件路径
define('_VIC_WORD_DICT_PATH_',__DIR__.'/Data/dict.igb');
