### ISSUE TITLE
运行  composer require lizhichao/word出错

### ISSUE THREAD

**Issue by bunian** [lizhichao/VicWord#5]
Using version ^1.3 for lizhichao/word
./composer.json has been updated
Root package 'lizhichao/word' cannot require itself in its composer.json
Did you accidentally name your root package after an external package?
![QQ图片20190404102150](https://user-images.githubusercontent.com/20419854/55525441-a0544700-56c3-11e9-8263-710d0a0a9f2d.png)

**Comment by lizhichao** [comment]
再试试
