### ISSUE TITLE
undefined igbinary_unserialize()

### ISSUE THREAD

**Issue by WildXBird** [lizhichao/VicWord#6]
PHP Fatal error:  Uncaught Error: Call to undefined function Lizhichao\Word\igbinary_unserialize() in C:\inetpub\wwwroot\VicWord\Lib\VicWord.php:31
Stack trace:
#0 C:\inetpub\wwwroot\VicWord\demo.php(19): Lizhichao\Word\VicWord->__construct('igb')
#1 {main}
  thrown in C:\inetpub\wwwroot\VicWord\Lib\VicWord.php on line 31

**Comment by liubaoqiang-go** [comment]
why
