### ISSUE TITLE
PHP 5.6.36 composer安装报错

### ISSUE THREAD

**Issue by getwebtools** [lizhichao/VicWord#8]
A PHP Error was encountered
Severity: Notice

Message: Use of undefined constant _VIC_WORD_DICT_PATH_ - assumed '_VIC_WORD_DICT_PATH_'

Filename: Lib/VicWord.php

Line Number: 28

**Comment by lizhichao** [comment]
需要定义 VIC_WORD_DICT_PATH 词典文件路径
